export { default as Home } from './Home'
export { default as Explore } from './Explore'
export { default as Likes } from './Likes'
export { default as SignUp } from './SignUp'
export { default as Login } from './Login'
